services:
  webapp:
    build: .
    container_name: webapp
    ports:
      - "8080:3000"
    environment:
      PORT: 3000
      LOG_PATH: /var/log/webapp/app.log
    volumes:
      - weblogs:/var/log/webapp
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3000/" ]
      interval: 2s
      timeout: 2s
      retries: 10

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3100/ready" ]
      interval: 2s
      timeout: 2s
      retries: 10

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - weblogs:/var/log/webapp
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      loki:
        condition: service_healthy
      webapp:
        condition: service_healthy

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "9090:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      loki:
        condition: service_healthy

volumes:
  weblogs:
